# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='hacer', max_length=128)),
                ('f', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
